
spring.application.name: 'micrometerDemo'
server.port: 8080
management.server.port: 8081
management.endpoints.enabled-by-default : true
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details : 'always'

management.metrics.web.server.auto-time-requests : true
management.metrics.web.server.requests-metric-name : 'foo.http.server.requests'

logging.level.root: INFO
logging.level.org.springframework: DEBUG